### ISSUE TITLE
It wont commit my pack. I made a new workspace, to refresh the client and the new packs didnt show up. I think theres a problem with gitpod!

### ISSUE THREAD

**Issue by SmplyVortexian** [ThisIsALegitUsername/Resent-web#10]

**Comment by ThisIsALegitUsername** [comment]
run the following commands:

```git remote add upstream https://github.com/ThisIsALegitUsername/Resent-web/```
```git pull upstream main```
```git add .```

and you should be able to commit like normal.

**Comment by SmplyVortexian** [comment]
what about if I want to commit something?

**Comment by ThisIsALegitUsername** [comment]
you click the commit button?
