### ISSUE TITLE
Unable to exit pause menu after getting disconnected from server while in settings

### ISSUE THREAD

**Issue by ZGStuff** [ThisIsALegitUsername/Resent-web#100]
So, I go to change my settings for BLOBCRAFT DUELS (1.8 pvp of course)...

*gets disconnected from idling*

*reconnects*

I'm in pause, nbd, been like that 800,000 times in 1.5.2
clicks return to game
doesn't work
reconnects
still doesn't work
?!?!?!?!? (rages for a minute)
and files this shitty bug report

**Comment by ThisIsALegitUsername** [comment]
This is because you clicked on the arc widget. It’s the purple circle thing in the bottom left. Don’t click it and you’ll be fine.
