### ISSUE TITLE
Yo, its me, Rice Help ples

### ISSUE THREAD

**Issue by TrulyVoid** [ThisIsALegitUsername/Resent-web#103]
ERROR: game cannot start, the "window.eaglercraftXOpts" variable is undefined
whenever I choose a texture pack and click launch that pops up and the game doesn't launch, is there a mistake e in the coding or something? <3 love you Nit please fix this though( i have done both normal and index html and neither work, 1.8 works fine but it does not have access to most servers, the only way I have been able to launch the client is the fps build.) thank you.

**Comment by ThisIsALegitUsername** [comment]
fixed
