### ISSUE TITLE
void again, something is wrong with reclient!

### ISSUE THREAD

**Issue by TrulyVoid** [ThisIsALegitUsername/Resent-web#105]
![image](https://user-images.githubusercontent.com/121824310/211017212-5c3158ba-ed92-4663-8448-551bca1e1a5d.png)
this shows up whenever i open resclient
(if that image doesnt appear for you this is the text in it:)
This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

451: DEPLOYMENT_DISABLED
Code: DEPLOYMENT_DISABLED
ID: 

If you are a visitor, contact the website owner or try again later.
If you are the owner, please [contact support](https://vercel.com/support/request).

**Comment by TrulyVoid** [comment]
> Try a different link

i did, i made an offline download i think this should work now for me but i cant 1.8

**Comment by gaster2411** [comment]
nice
can you guys mediafire or google drive the file download
also here https://3kh0.github.io/projects/minecraft-18/index.html

**Comment by SmplyVortexian** [comment]
what are the different links?

**Comment by SmplyVortexian** [comment]
my acc has been blocked too! bro

**Comment by 3kh0** [comment]
Use 3kh0.github.io geez

**Comment by SmplyVortexian** [comment]
my school blocked that

**Comment by 3kh0** [comment]
use 2kh0.github.io
use 1kh0.github.io

more links: discord.gg/3kh0

**Comment by SmplyVortexian** [comment]
my school blocked all your links. I tried from 1kh0 to like 9, all are blocked

**Comment by SmplyVortexian** [comment]
i found your 9kh0 website works, but i hate the part where i get a fullscreen ad that says my files are encrypted. remove that pls

**Comment by 3kh0** [comment]
When does that happen???

**Comment by SmplyVortexian** [comment]
idk something popped up on your tab specifically and said my files were encrypted. But they werent obv

**Comment by 3kh0** [comment]
you clicked on the fake virus one lol
