### ISSUE TITLE
End of Stream Error

### ISSUE THREAD

**Issue by Nightguard2103** [ThisIsALegitUsername/Resent-web#108]
The new 1.8 URL https://asianf4rmer.vercel.app/1.8/index.html# Is extremely laggy on the lowest video settings and will kick you from the server with an End of Stream error. Using chrome book on Google browser.
![image](https://user-images.githubusercontent.com/122903645/212945786-c7defdc4-b9c9-45cf-9ae5-287f13d37b0e.png)

**Comment by ThisIsALegitUsername** [comment]
That's not the new URL. join the discord to find new offline downloads.
