### ISSUE TITLE
New Resent website: Singleplayer crash

### ISSUE THREAD

**Issue by SuperMarioMaker64** [ThisIsALegitUsername/Resent-web#110]
In the new website for Resent client (https://eaglercraft.ru/) since the old one is disabled, I tried multiple times to access singleplayer for 1.5.2 but it crashes every time. It even says to refresh if it happened the first time but it happens every time. Please fix it, I want to play singleplayer for Resent 1.5.2 since 1.8.8 doesn't have it yet. I mostly use it because of the mods it has in the GUI menu.

**Comment by SuperMarioMaker64** [comment]
The cosmetics in the new version of Resent 1.8 on the same website mentioned above is broken. The glasses don't come off when you uncheck "glasses" or turn off the cosmetics setting.

**Comment by 3kh0** [comment]
dont use that site, ez
