### ISSUE TITLE
Hiring u

### ISSUE THREAD

**Issue by Maxwick456** [ThisIsALegitUsername/Resent-web#114]
READ EVERYHIING!!!
Okie,  I have a company(strongdogLLC) also strongdog.com
You are hired, And you are allowed to pick ANY laptop on dell.com (for work)
We can write it off
https://turbotax.intuit.com/tax-tips/self-employment-taxes/video-can-i-deduct-the-cost-of-a-new-computer-on-my-taxes/L555e77AN
So it cool😎

Oh and llc official documents are 
https://secure.utah.gov/bes/displayDetails.html

**Comment by ThisIsALegitUsername** [comment]
whar

**Comment by 3kh0** [comment]
BO WHO TF ARE YOU

**Comment by Maxwick456** [comment]
A cool huaman

**Comment by Maxwick456** [comment]
@ThisIsALegitUsername 
Ok u are hired with that u get free company pc

PC:
Laptop:
Estimated Value $8,211.26
Price: $2,873.47
Specs:
CPU: 11th Gen Intel® Core™ i9-11950H, vPro® (24MB cache, 8 cores, 16 threads, 2.60 GHz to 5.00 GHz Turbo)
OS: Windows 11 Pro, English, French, Spanish
GPU: NVIDIA® Quadro® T1200, 4 GB GDDR6
RAM: 128 GB, 4 x 32 GB, DDR4, 3200 MHz
HDD 1: 1 TB, M.2 2280, Gen 4 PCIe x4 NVMe, SSD
Personal HDD: M.2 2280 512 GB, Gen 4 PCIe x4 NVMe, Solid State Drive
M.2 chip: Intel Wi-Fi 6E AX210 Wireless Card with Bluetooth 5.2
Battery: 6 Cell, 95 Wh, ExpressCharge™ Capable
MOBILE DATA: 5G - Qualcomm® Snapdragon™ X55 Global 5G (DW5930e), Verizon

**Comment by Maxwick456** [comment]
Also I am Maximus you know me :)

**Comment by Maxwick456** [comment]
From DPMS bus

**Comment by ThisIsALegitUsername** [comment]
yes i do know you id appreciate it if you didnt yk leak our school to the public

**Comment by 3kh0** [comment]
LOL

**Comment by Maxwick456** [comment]
Yeah Ok

**Comment by Maxwick456** [comment]
i sent it to your school email

**Comment by ThisIsALegitUsername** [comment]
ok
