### ISSUE TITLE
MERGE MY PULL REQUESTS LOL i fixed the dissapearing changelog issue :trol:

### ISSUE THREAD

**Issue by legendcuzican13** [ThisIsALegitUsername/Resent-web#47]
hehehehhwaw

**Comment by envyluv** [comment]
where is the pr

**Comment by legendcuzican13** [comment]
![Screenshot 2022-11-21 12 57 34 PM](https://user-images.githubusercontent.com/108838775/203137187-e204deb0-3ac4-4eb8-96e8-5948f11b0ce6.png)

**Comment by legendcuzican13** [comment]
@envyluv

**Comment by envyluv** [comment]
oh its fixed anyways
