### ISSUE TITLE
how do i make my own vercel deploys from thi , because precision just got blocked today and im worried resent will too

### ISSUE THREAD

**Issue by SmplyVortexian** [ThisIsALegitUsername/Resent-web#51]

**Comment by ThisIsALegitUsername** [comment]
make a vercel account, import this repo, set the output directory in build and output settings to “javascript”

**Comment by SmplyVortexian** [comment]
ok

**Comment by SmplyVortexian** [comment]
how do i install @vercel/analytics
in other words, how do i get to whatever terminal or package manager to install it on vercel.

**Comment by Ironbrodiet** [comment]
Can I have some of your deploy links?

**Comment by Ironbrodiet** [comment]
resentclient.vercel.app
