### ISSUE TITLE
Servers simply not working?

### ISSUE THREAD

**Issue by Ironbrodiet** [ThisIsALegitUsername/Resent-web#62]
It may be because the school had updated the firewall so this isn't working. Do any of you have proxy links I can try? Literally all of mine have become blocked.

**Comment by 3kh0** [comment]
Yeah for me I can still join servers

**Comment by Ironbrodiet** [comment]
Can I have some proxy links? Also idk if this is a issue or not but yesterday I was getting a solid 60-80 FPS and today I'm getting 15 (with the same texture pack and same settings)

**Comment by Ironbrodiet** [comment]
Nevermind, I'm back up to 30-40 FPS

**Comment by Ironbrodiet** [comment]
Ok I realized it was because I had 50 tabs open (from school). I deleted all of those, I'm back up to 60 fps.
