### ISSUE TITLE
Maybe add new servers to the server list.

### ISSUE THREAD

**Issue by Ironbrodiet** [ThisIsALegitUsername/Resent-web#63]
Some like Asspixel, Aeon, and so forth. I understand you can just add your own and it's really simple, but I think for some less 'advanced' users this would be really helpful.
Adding this to the source code should be quite simple also.

I understand if you are not able to do this, but as I said, this would be really helpful.
Thank you!

**Comment by Ironbrodiet** [comment]
Basically all the precision client servers + some others.

**Comment by DevNeoGM** [comment]
dude u are joking right?

**Comment by the9four** [comment]
🗿

**Comment by Ironbrodiet** [comment]
no im not what am i not getting here

**Comment by Ironbrodiet** [comment]
also why is blobcraft not working

**Comment by 3kh0** [comment]
#59
