### ISSUE TITLE
MOds

### ISSUE THREAD

**Issue by fnfgo** [ThisIsALegitUsername/Resent-web#64]
how do you add mods to this?

**Comment by Wildtick** [comment]
your so stupid

**Comment by fnfgo** [comment]
i know how to code

**Comment by ThisIsALegitUsername** [comment]
write the code for the mod and dm it to me on discord. I will add it.

**Comment by fnfgo** [comment]
Im on a school chromebook discords blocked -_-

**Comment by ThisIsALegitUsername** [comment]
then put the code in here
