### ISSUE TITLE
(Most) servers don't work.

### ISSUE THREAD

**Issue by Ironbrodiet** [ThisIsALegitUsername/Resent-web#67]
I don't know if this is just a 'me' problem, but servers don't work on Resent Client (besides blobcraft and legend SMP).
The reason I know it is just Resent Client is because I used a normal eaglercraft 1.5.2 link and all the server IP's I put in worked.

An example is of the photos below. For one of them, Hyper Network is working (The normal eaglercraft link). For the one that is Resent Client (the one with the texture pack), Hyper Network isn't working. If any of you know the fix to this problem, please tell me. Thanks!
![Screenshot 2022-12-10 7 21 33 PM](https://user-images.githubusercontent.com/95990226/206884772-e5ec3dfe-b8ca-4c7a-8976-cafc8662be70.png)
![Screenshot 2022-12-10 7 19 48 PM](https://user-images.githubusercontent.com/95990226/206884775-9b620fd5-3736-4dfa-a2f0-84abbfd7f523.png)

**Comment by Ironbrodiet** [comment]
I forgot to mention that yes, I did take the screenshots at the same time, and yes, I did check to see if the IPs were the same.

**Comment by NeoGMDev** [comment]
I think my server wasen't working in that because i forgot to update my allow clients & i forgot to add resent to it 💀

**Comment by Ironbrodiet** [comment]
Huh

**Comment by Ironbrodiet** [comment]
Can you add resent to it now?

**Comment by 3kh0** [comment]
For me it works...

**Comment by Ironbrodiet** [comment]
Yeah, I figured that out by using /domain.  Like for me, asspixel doesn't work on resent. I've played on asspixel (using a different client) and I did /domain (on random people) and I've found people using resent client.

**Comment by Ironbrodiet** [comment]
**Recently, I have been led to believe it has something to do with firewalls or school blockers.**

Blobcraft and Legend SMP work at home, but when I went to school and loaded up resent, Blobcraft and Legend SMP weren't working.

**Comment by Ironbrodiet** [comment]
> I think my server wasen't working in that because i forgot to update my allow clients & i forgot to add resent to it 💀

Also, I know this has nothing to do with this issue but-
 **MY MVP++ RANK IS GONE** (on my account _Brxdie_)
Can you explain?

**Comment by ThisIsALegitUsername** [comment]
Based on the information that you have provided me, it appears that servers don't work because your school blocked them.
