### ISSUE TITLE
Unable to generate offline.html?

### ISSUE THREAD

**Issue by TG20YT** [ThisIsALegitUsername/Resent-web#71]
Hello! I was attempting to generate an html file for Resent Client, but for some reason python gives me the "Killed" output and then stops. I'm using the SuperiorFPS, Asda 16x Short Swords, and Resent 16x packs. I was able to get a successful file, but when downloading it,chrome says "Download failed. Chrome cannot find the file on the server." I'm doing this on a Chromebook in the codespaces in the subfolder javascript/gen and the file is gen.py, command is python3 gen.py

Is there something I'm doing wrong?

Here is the terminal output:

@TG20YT ➜ /workspaces/Resent-web/javascript/gen (main ✗) $ python3 gen.py

Killed

@TG20YT ➜ /workspaces/Resent-web/javascript/gen (main ✗) $

**Comment by Alex-A137** [comment]
im having the same problem, but they are currently ignoring me.
can't help sorry

**Comment by ThisIsALegitUsername** [comment]
If your offline download says killed after you run the command, that means you selected too many texture packs and the file is too large, therefore causing github codespaces' resources to run out. However, you only selected 3 texture packs, so it's strange for this to occur. I would suggest using gitpod as an alternative.
